### ISSUE TITLE
[ BUG ] `/users/:id` results in an unanswered request

### ISSUE THREAD

**Issue by joseywoermann** [ScarletAI/Scarlet#4]
**Describe the bug**
When sending a `GET` to `/users/:id`, the API does not return a response which leads to an unanswered request.

**To Reproduce**
1. Send a `GET` request [as described in the docs](https://github.com/ScarletAI/Scarlet#usage) to the API, for example like this:
```js
import fetch from "node-fetch";

const res = await fetch("https://api.scarletai.xyz/users/1234567890", {
    body: JSON.stringify({
        username: "your_username",
        password: "your_password",
        token: "y.ourtoken_here",
    })
});
const data = await res.json();
console.log(data);
```
2. Observe that the API does not respond to the request.

**Expected behavior**
As mentioned in the documentation, a `200 OK` should be returned, alongside the credentials for the given user.

**Actual behavior**
No response is sent, resulting in an unanswered request (see screenshot).

**Screenshots**

![image](https://user-images.githubusercontent.com/67111271/146447077-30172012-27f8-45db-9cd5-e472db67eafd.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Home 21H1 (19043.1348)
 - Browser [e.g. chrome, safari] N/A, using the "Thunder Client" VS Code extension as an HTTP client.
 - Version [e.g. 22] N/A

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] **Are you sure that this should be in the template?**

**Additional context**
[This](https://github.com/ScarletAI/Scarlet/blob/master/users/controllers/users.controller.js#L87) might be the reason why, I don't think that `user` is defined. Alternatively, #5 might be the issue and the HTTP client I used simply doesn't have a proper error handler for that situation.

**Comment by KazutoKashima** [comment]
Hey Josey!
Thanks for bringing this up, seems like this bug is back at it again 🤣 it was originally patched but I'll look into it none-the-less!

**Comment by KazutoKashima** [comment]
I think I have solved the issue 🤔
Leaving the issue open in case it appears again within the next few days

**Comment by joseywoermann** [comment]
> I think I have solved the issue 🤔 Leaving the issue open in case it appears again within the next few days

The bug is still there, exactly like before. (Tested with both Thunder Client & Axios).

**Comment by KazutoKashima** [comment]
@joseywoermann When ready, try again, I would like to know if the bug I'm currently experiencing is me forgetting my password or an issue with authentication of passwords

**Comment by joseywoermann** [comment]
> @joseywoermann When ready, try again, I would like to know if the bug I'm currently experiencing is me forgetting my password or an issue with authentication of passwords

Seems like an auth issue, I get a 401 back even tho my credentials are all correct.

**Comment by KazutoKashima** [comment]
Alright, it might be an issue with how I'm checking with the auth, I'll give a few tweaks later on today (after work probably), and see if i can fix that up

**Comment by KazutoKashima** [comment]
I believe it has been fixed now, all tests have been successful on client and local, and that's with creating a few test accounts to attempt this with as well as using my own. 
Try it on your side, fingers crossed that it should all work

**Comment by KazutoKashima** [comment]
Update on Database: Issue seems to be temporary failure in resolution, seems to be resolved now.

**Comment by joseywoermann** [comment]
> I believe it has been fixed now, all tests have been successful on client and local, and that's with creating a few test accounts to attempt this with as well as using my own. Try it on your side, fingers crossed that it should all work
> 
> EDIT: There seems to be an issue with the database working on it now

I created a new test account, and it worked fine. However, it doesn't seem to work with my main account (getting HTTP 524s).

**Comment by KazutoKashima** [comment]
Yeah as discussed in the server, it seemed to be a DB issue and it now not wanting to use the hashes and tokens from old accounts, if you have a secondary account already setup, shoot me a DM so I can avoid deleting it by accident.

I'll begin work on the HEADER requests for `GET` after tomorrow, which may introduce breaking changes, if reviews suggest removing the old methods

**Comment by KazutoKashima** [comment]
Issue wasn't related to tokens, but to the UID, forgot to update the docs to reflect that lmao
