### ISSUE TITLE
[ BUG ] `/scarlet/analyze` does not check credentials

### ISSUE THREAD

**Issue by joseywoermann** [ScarletAI/Scarlet#9]
**Describe the bug**
When interacting with `/scarlet/analyze`, you can pass any string as the `token`, and the API will return a response even if the token is incorrect. You don't even have to pass a `username`.

**To Reproduce**
1. Send a `POST` request to `/scarlet/analyze` as documented in the docs.
2. Observe that you get the expected result when passing correct credentials.
3. Send a `POST` request to `/scarlet/analyze`, but this time, pass a random string as the `token`.
4. Observe that you get the same result, even though credentials are incorrect.
5. Send a `POST` request to `/scarlet/analyze`, but this time, remove the `username` field.
6.  Observe that you get the same result, even though no `username` has been defined.

**Expected behavior**
The API should reject the request because the credentials are incorrect.

**Examples**
For 3.:
```json
{
    "username": "something",
    "token": "Never gonna give you up",
    "content": "I am happy"
}
``` 
For 5.:
```json
{
    "token": "Never gonna give you up",
    "content": "I am happy"
}
``` 

**Additional context**
Maybe something in the database broke while trying to fix #4?

**Comment by KazutoKashima** [comment]
Thanks for bringing the token to my attention, but as for the username/password/etc, `scarlet/analyze` doesn't require those (for simplicity when integrating the API into other services).
But the token issue seems to be a me issue 🤣 i may or may not have forgotten to check the DB for the tokens

**Comment by KazutoKashima** [comment]
Hmm, doesn't seem to be checking the tokens at all, could you review the semantics folder to see if there's any issues that I may have missed?

**Comment by joseywoermann** [comment]
The only place where it could go wrong is [here](https://github.com/ScarletAI/Scarlet/blob/master/users/models/users.model.js#L43), where you convert it to a boolean.

If mongoose returns an empty array or an empty object in case no user with that token is found, that's the issue. (Empty arrays & objects are considered "truthy" and will therefore convert to `true`, even though you would want it to return `false` in that case.

**Comment by joseywoermann** [comment]
If mongoose really returns an empty array instead of `null` or `undefined`, I would change the method to this:

```js
 ​exports​.​findByToken​ ​=​ ​(​token​)​ ​=>​ ​{ 
 ​    ​let​ ​find​ ​=​ ​User​.​find​(​{​token​: ​token​}​)​; 
     if (find == []) return false;
 ​    ​​return​ ​true​,​ ​find​;
 ​}
```

(Make sure mongoose really returns an empty array if no user with that token is found first.)

**Comment by KazutoKashima** [comment]
Fixed underlying issue related to `findByToken` and a few other getters, decided to make `scarlet/analyze` open without token, to make it more open for users, closing this now

**Comment by joseywoermann** [comment]
> decided to make `scarlet/analyze` open without token

I tested it today with a payload like this, but it gave me a `401 - No AI Token found`.

Request body:
```json
{
    "content": "hello there!"
}
```
Response body:
```json
{
  "status": 401,
  "message": "No AI Token found"
}
```

**Comment by KazutoKashima** [comment]
Uhhhhh-
Alright, reopening the issue and looking into it now
hmu on telegram or twitter so we can discuss it in realtime
Twitter: @Kazutokashima
Telegram: https://t.me/kaz_phoenix

**Comment by joseywoermann** [comment]
Resolved.
